// flow-typed signature: 1ff9b8a4310567661183c2bd75119ed8
// flow-typed version: <<STUB>>/appr_v^1.0.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'appr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'appr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'appr/scripts/config' {
  declare module.exports: any;
}

declare module 'appr/scripts/config/circle' {
  declare module.exports: any;
}

declare module 'appr/scripts/config/default' {
  declare module.exports: any;
}

declare module 'appr/scripts/config/travis' {
  declare module.exports: any;
}

declare module 'appr/scripts/log' {
  declare module.exports: any;
}

declare module 'appr/scripts/post-deploy' {
  declare module.exports: any;
}

declare module 'appr/scripts/pre-deploy' {
  declare module.exports: any;
}

declare module 'appr/scripts/spawn' {
  declare module.exports: any;
}

declare module 'appr/scripts/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'appr/index' {
  declare module.exports: $Exports<'appr'>;
}
declare module 'appr/index.js' {
  declare module.exports: $Exports<'appr'>;
}
declare module 'appr/scripts/config.js' {
  declare module.exports: $Exports<'appr/scripts/config'>;
}
declare module 'appr/scripts/config/circle.js' {
  declare module.exports: $Exports<'appr/scripts/config/circle'>;
}
declare module 'appr/scripts/config/default.js' {
  declare module.exports: $Exports<'appr/scripts/config/default'>;
}
declare module 'appr/scripts/config/travis.js' {
  declare module.exports: $Exports<'appr/scripts/config/travis'>;
}
declare module 'appr/scripts/log.js' {
  declare module.exports: $Exports<'appr/scripts/log'>;
}
declare module 'appr/scripts/post-deploy.js' {
  declare module.exports: $Exports<'appr/scripts/post-deploy'>;
}
declare module 'appr/scripts/pre-deploy.js' {
  declare module.exports: $Exports<'appr/scripts/pre-deploy'>;
}
declare module 'appr/scripts/spawn.js' {
  declare module.exports: $Exports<'appr/scripts/spawn'>;
}
declare module 'appr/scripts/utils.js' {
  declare module.exports: $Exports<'appr/scripts/utils'>;
}
