// flow-typed signature: 339c9b934231fd16c90f299a8c8a3ee6
// flow-typed version: <<STUB>>/jest-expo_v~1.0.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-expo/src/exponentModules' {
  declare module.exports: any;
}

declare module 'jest-expo/src/setup' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-expo/src/exponentModules.js' {
  declare module.exports: $Exports<'jest-expo/src/exponentModules'>;
}
declare module 'jest-expo/src/setup.js' {
  declare module.exports: $Exports<'jest-expo/src/setup'>;
}
