// flow-typed signature: d0eb94ff7973ffcd32987a812c6275cb
// flow-typed version: <<STUB>>/portable-fetch_v^3.0.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'portable-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'portable-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'portable-fetch/fetch-bower' {
  declare module.exports: any;
}

declare module 'portable-fetch/fetch-npm-browserify' {
  declare module.exports: any;
}

declare module 'portable-fetch/fetch-npm-node' {
  declare module.exports: any;
}

declare module 'portable-fetch/fetch-npm-react-native' {
  declare module.exports: any;
}

declare module 'portable-fetch/test/api.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'portable-fetch/fetch-bower.js' {
  declare module.exports: $Exports<'portable-fetch/fetch-bower'>;
}
declare module 'portable-fetch/fetch-npm-browserify.js' {
  declare module.exports: $Exports<'portable-fetch/fetch-npm-browserify'>;
}
declare module 'portable-fetch/fetch-npm-node.js' {
  declare module.exports: $Exports<'portable-fetch/fetch-npm-node'>;
}
declare module 'portable-fetch/fetch-npm-react-native.js' {
  declare module.exports: $Exports<'portable-fetch/fetch-npm-react-native'>;
}
declare module 'portable-fetch/test/api.test.js' {
  declare module.exports: $Exports<'portable-fetch/test/api.test'>;
}
