// flow-typed signature: 07610b82be384fd806e1f05532896ecc
// flow-typed version: <<STUB>>/react-native-looped-carousel_v^0.1.7/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-looped-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-looped-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-looped-carousel/index' {
  declare module.exports: $Exports<'react-native-looped-carousel'>;
}
declare module 'react-native-looped-carousel/index.js' {
  declare module.exports: $Exports<'react-native-looped-carousel'>;
}
